version: "3.2"
services:
  nodejs:
    container_name: trafi-dummy-node
    image: nuc:5000/trafi-dummy-node
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8002:8080"
      - "9229:9229"
    command:
      - node
      - "--inspect-brk=0.0.0.0"
      - "."